#spring:
#  datasource:
#    username: root
#    password: password
#    url:jdbc: msql://localhost:3306/spring-boot
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jta:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
